name: Release

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      versionCode: ${{ steps.set_version.outputs.versionCode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Version
        id: set_version
        run: |
          git describe --tags --abbrev=0
          git rev-list HEAD --count
          echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          echo "versionCode=$((1000 + $(git rev-list HEAD --count)))" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Display artifacts
        run: ls -R
      - name: zip
        id: zip
        run: |
          for dir in Wallet-Fix-*; do
            if [ -d "$dir" ]; then
              echo "----- Zip $dir -----"
              (cd $dir && zip -r9 "../$dir.zip" ./*)
            fi
          done
          echo "release=$(ls Wallet-Fix-*-release.zip)" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.setup.outputs.version }}
          files: |
            Wallet-Fix-*.zip

      - name: write update.json
        run: |
          version="${{ needs.setup.outputs.version }}"
          versionCode="${{ needs.setup.outputs.versionCode }}"
          zipUrl="https://github.com/geniucker-dev/WalletFix4OOS14/releases/download/${version}/${{ steps.zip.outputs.release }}"
