name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag
        id: set_tag
        run: |
          echo "tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_OUTPUT

  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
      - name: Display artifacts
        run: ls -R
      - name: zip
        run: |
          for dir in Wallet-Fix-*; do
            if [ -d "$dir" ]; then
              echo "----- Zip $dir -----"
              (cd $dir && zip -r9 "../$dir.zip" ./*)
            fi
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Wallet-Fix-*.zip
